### REST CLIENT Extension
@hostname = http://localhost
@port = 4000
@host = {{hostname}}:{{port}}
@base= api/auth
@contentType = application/json


// Login User
POST {{host}}/{{base}} HTTP/1.1
content-type: {{contentType}}

{
  "email": "sam@email.com",
  "password":"Sam12345"
}
###

// Register New User
POST {{host}}/{{base}}/register HTTP/1.1 
content-type: {{contentType}}

{
  "name": "Samantha",
  "email": "sam@email.com",
  "password":"Sam12345"
}

###
GET {{host}}/{{base}}/validate HTTP/1.1
// Headers
x-token:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTdiZjczNGFmZWE0NDAyMmY3YTg0MzAiLCJuYW1lIjoiU2FtYW50aGEiLCJpYXQiOjE2MzU1MTQ0OTEsImV4cCI6MTYzNTUyMTY5MX0.Vb2lXrdWbWtbGRU68QnuA9wlxltCk2kZ3kktgq8YPNE'

